version: '3'

services:
  backend:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db

  db:
    image: 'postgres:14.0'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_movies
